name: super_time
description: "Introducing SuperTime: the ultimate solution for simplifying time management in Dart and Flutter. With SuperTime, effortlessly handle time-related tasks with intuitive APIs for time representation, manipulation, and formatting. Seamlessly integrate SuperTime into your Flutter projects and enjoy robust timezone support, ensuring accurate time representation across different regions. Say goodbye to time-related headaches and hello to streamlined time management with SuperTime."
version: 0.0.2+1
homepage: https://github.com/D3R50N/super_time.git
repository: https://github.com/D3R50N/super_time.git

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
