name: super_time
description: "The ultimate solution for simplifying time management in Dart and Flutter. Handle time-related tasks with intuitive APIs for time representation and formatting."
version: 0.0.2+4
homepage: https://github.com/D3R50N/super_time.git
repository: https://github.com/D3R50N/super_time.git

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
